[package]
name = "libbinder-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.104"
either = "1.18.0"
libbinder = { path = "../libbinder" }
libbinder-basic = { version = "0.1.0", path = "../extras/libbinder-basic", features = ["macros"] }
nix = { version = "0.31.3", features = ["process", "user"] }

